### ISSUE TITLE
Item edit error

### ISSUE THREAD

**Issue by amandafrench** [gsoules/AvantRelationships#1]
I'm getting the error `Parse error: syntax error, unexpected T_BOOLEAN_AND, expecting ')' in /home3/alfrench/public_html/booknetworks.org/plugins/AvantRelationships/models/RelatedItemsTree.php on line 136`

when I try to edit items once AvantRelationships is installed. Uninstalling the plugin (and deleting its data) brings the normal item edit function back: reinstalling the plugin breaks item edit again. Help? This seems like a fantastic, really sophisticated semantic plugin for relationship viz.

**Comment by amandafrench** [comment]
BTW I was running Omeka 2.6 -- I rolled back to 2.5.1 but that didn't work either. Also can't delete items.

**Comment by gsoules** [comment]
I have released v2.0.0 versions of AvantRelationships and AvantCommon, along with other plugins in the same family. I apologize for the long delay in responding to you -- I only now saw this issue (still learning my way around github).

**Comment by amandafrench** [comment]
@gsoules No problem, George. Looking forward to trying the new version and seeing if that resolves it, but it might be awhile.
